// angular2-front/src/app/adminlte/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'adminlte-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class AdminLTEFooterComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> Ang. 0.0.1-alpha
  </div>
  <strong>Copyright &copy; 2017 <a>Nendoroids db</a>.</strong> All rights reserved.
</footer>

// vuejs-front/src/components/layouts/Footer.vue
<template>
  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Manage your Nendoroids collection
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2018 <a href="#">Nendoroids db</a>.</strong> All rights reserved.
  </footer>
</template>

<script>
  export default {
    name: 'Footer',
    data () {
      return {
      }
    }
  }
</script>
